name: ma_crm_panel
description: "پنل CRM مالک — MA Warehouse (دسکتاپ ویندوز، فقط‌خواندنی)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  dio: ^5.11.0
  flutter:
    sdk: flutter
  shamsi_date: ^1.1.1
  shared_preferences: ^2.5.5
  socket_io_client: ^3.1.6

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
